Update README.md
OSCA-Ado-Ekiti/tech-companies-in-africa pull request #95
Opened 2023-10-02 19:22 UTC by Victorayo

Added a company that starts with letter O in Opay, a Fintech company in Nigeria.

2023-10-02 20:42 UTC, OSCA-Ado-Ekiti commented
@Victorayo is this PR still valid, if it is not you can close it.

2023-10-02 22:22 UTC, Victorayo commented
> @Victorayo is this PR still valid, if it is not you can close it.

It's valid @OSCA-Ado-Ekiti

2023-10-04 11:22 UTC, gray-adeyi requested changes

2023-10-04 11:22 UTC, gray-adeyi commented on README.md
> +  - Industry: Fintech
Please also include this your new addition to the `techCompanies.js` file

2023-10-04 12:12 UTC, closed without merging